### ISSUE TITLE
.pairs with different email addresses does not seem to work

### ISSUE THREAD

**Issue by danieroux** [RoboPlugins/git-pair.idea#12]
This works well:

```
pairs:
    as: Alice Smith; alice
    bd: Bob Doe; bob

email:
    domain: example.com
```

The problem is that not all developers on the current project is from the same company, and have different email addresses. This, does not work:

```
pairs:
    as: Alice Smith
    bd: Bob Doe

email_addresses:
    as: alice.smith@example.com
    bd: bob.doe@another.corp
```

Does not work means: I can't click on the names to get tick marks next to the current pair.
